import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/comps/Footer";
import Header from "@/comps/Header";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
